### ISSUE TITLE
Focus en hover ontbreken

### ISSUE THREAD

**Issue by vasilisvg** [Murderlon/css-to-the-rescue#1]
De interface leeft niet. 
- Als ik met mijn muis over interactieve elementen ga zoals buttons en links dan is er geen enkele aanwijzing dat ik er iets mee kan doen. Gebruik dus hover.
- Als ik door de interface heen tab met mijn toetsenbord dan is er geen enkele indicatie van waar de focus is. Dat kan veel duidelijker!

**Comment by Murderlon** [comment]
Done!
